== Parameters

A command receives several arguments. Every argument must obey the rules of its corresponding _parameter definition_.

A _parameter definition_ is a set of definitions regarding a single parameter for a specific command.

A command must have the same amount of arguments as its amount of parameter definitions, unless the missing arguments correspond to _optional parameters_ (defined below).

If a variable is used in the same command both as an input and as an output, the input shall be evaluated before any output is assigned to the variable.

=== String Constants

A _string constant_ is a name associated with an integer value. Such association is known in the translation environment.

An _enumeration_ is a collection of string constants.

A parameter definition can have an associated enumeration. A string constant is said to be a match if an identifier in an argument refers to a name in its parameter's enumeration.

There is an special enumeration called the _global string constants enumeration_ which semantics are defined along this specification. Other enumerations can be defined by an implementation.

If a parameter definition specifies an enumeration, the global string constants enumeration cannot be matched in the said parameter.

=== Entities

An _entity_ is an object of the execution environment. Each entity has an _entity type_, which defines its purposes.

A parameter definition can have an associated entity type.

An entity can be assigned to a variable. In such case, the variable is said to be of that specific entity type from that line of code on. Previous lines of code are not affected.

If an entity type is associated with an parameter and a variable is used as argument, the variable must have the same entity type as the parameter.

Further semantics for entities are defined along this document.

=== Parameter Types

==== INT

An _INT parameter_ accepts an argument only if it is an integer literal or an identifier matching a global string constant.

==== FLOAT

A _FLOAT parameter_ accepts an argument only if it is a floating-point literal.

==== VAR_INT

A _VAR_INT parameter_ accepts an argument only if it is an identifier referencing a global variable of integer type.

==== VAR_FLOAT

A _VAR_FLOAT parameter_ accepts an argument only if it is an identifier referencing a global variable of floating-point type.

==== LVAR_INT

A _LVAR_INT parameter_ accepts an argument only if it is an identifier referencing a local variable of integer type.

==== LVAR_FLOAT

A _LVAR_FLOAT parameter_ accepts an argument only if it is an identifier referencing a local variable of floating-point type.

==== INPUT_INT

An _INPUT_INT parameter_ accepts an argument only if it is an integer literal or an identifier either matching a string constant, global string constant or referencing a variable of integer type (in this order).

==== INPUT_FLOAT

An _INPUT_FLOAT parameter_ accepts an argument only if it is a floating-point literal or an identifier referencing a variable of floating-point type.

==== OUTPUT_INT

An _OUTPUT_INT parameter_ accepts an argument only if it is an identifier referencing a variable of integer type.

If an entity type is associated with the parameter, the variable must have the same entity type as the parameter, unless there is no entity type associated with the variable. In the latter case, the parameter's entity type is assigned to the variable.

==== OUTPUT_FLOAT

An _OUTPUT_FLOAT parameter_ accepts an argument only if it is a identifier referencing a variable of floating-point type.

==== LABEL

A _LABEL parameter_ accepts an argument only if it is an identifier whose name is a label in the multi-file.

==== TEXT_LABEL

A _TEXT_LABEL parameter_ accepts an argument only if it is an identifier. If the identifier begins with a dollar character (`$`), its suffix must reference a variable of text label type and such a variable is the actual argument. Otherwise, the identifier is a text label.

==== VAR_TEXT_LABEL

A _VAR_TEXT_LABEL parameter_ accepts an argument only if it is an identifier referencing a global variable of text label type.

==== LVAR_TEXT_LABEL

A _LVAR_TEXT_LABEL parameter_ accepts an argument only if it is an identifier referencing a local variable of text label type.

==== STRING

A _STRING parameter_ accepts an argument only if it is a string literal.

==== Optional Parameters

Additionally, the following parameters are defined as behaving equivalently to their correspondent parameters above, except that in case an argument is absent, parameter checking stops as if there are no more parameters to be checked.

* _VAR_INT_OPT_
* _VAR_FLOAT_OPT_
* _LVAR_INT_OPT_
* _LVAR_FLOAT_OPT_
* _VAR_TEXT_LABEL_OPT_
* _LVAR_TEXT_LABEL_OPT_
* _INPUT_OPT_

Such parameters are always trailing parameters.

The _INPUT_OPT parameter_ accepts an argument only if it is an integer literal, floating-point literal, or identifier referencing a variable of integer, floating-point or text label type.
