[[definitions]]
== Terms and Definitions

For the purposes of this document, the terms and definitions given in <<itvocabulary>> and the following apply.

Terms that are used only in a small portion of this document are defined where they are used and italicized where they are defined.

Because of the lack of information about the original language, some terms in this document are community defined.

behaviour:: external appearance or action.

behaviour, implementation-defined:: behavior specific to an implementation, where that implementation must document that behavior.

behaviour, undefined:: behavior which is not guaranteed to produce any specific result.

behaviour, unspecified:: behavior for which this specification provides two or more possibilities and imposes no further requirements on which is chosen in any instance.

constraint:: restriction, either syntactic or semantic, on how language elements can be used.

must:: describes an absolute requirement. synonymous with *shall*.

must not:: describes an absolute prohibition. synonymous with *shall not*.

should:: describes a recommended but not absolutely necessary requirement.

should not:: describes an unrecommended but not absolutely prohibited requirement.

may:: describes an optional requirement.

execution environment:: the software on which the result of translation is executed on.

translation environment:: the software on which the language is translated for use by an execution environment.

implementation:: particular set of software, running in a particular translation environment under particular control options, that performs translation of programs for, and supports execution of commands in, a particular execution environment.

well-formed program:: program constructed according to the synctatic and semantic rules as defined by this specification.

ill-formed program:: program that is not well-formed.

value:: precise meaning of the contents of a name when interpreted as having a specific type.

argument:: a value passed to a command that is intended to map to a corresponding parameter.

parameter:: the value to be received in a specific argument of a command.

in-house compiler:: the translation environment used by DMA Design. this document refers more specifically to <<references,Official GTA3 Script Compiler V413>>.

