= GTA3script Specification
:toc: macro
:toc-title:
:toclevels: 9
:sectnums:
//:revnumber: {release-version}
:revdate: {localdate}
:nofooter:
:sectanchors:
:idprefix:
:idseparator: -
:xrefstyle: short
:!section-refsig:


NOTE: This is a draft. It may be wrong, incomplete and subject to change.

toc::[]

// Introduction

:!sectnums:

include::introduction.adoc[]

:sectnums:

include::scope.adoc[]

include::definitions.adoc[]

include::general.adoc[]

// Language

include::concepts.adoc[]

include::elements.adoc[]

include::parameters.adoc[]

include::alternators.adoc[]

include::expressions.adoc[]

include::statements.adoc[]

include::structure.adoc[]

// Supporting Commands

include::command-def.adoc[]

include::alternator-def.adoc[]

// Appendix

include::appendix-grammar.adoc[]

include::appendix-grammar-lex.adoc[]

include::appendix-ambiguity.adoc[]

include::appendix-miss2.adoc[]

include::references.adoc[]


TODO list of special command names (user cannot write these, include AND/OR/NOT)
TODO label semantics of start new script (GTA3 allows label: {})
TODO SAN ANDREAS ALLOWS IDENTIFIERS TO BEGIN WITH UNDERSCORES
TODO remember GTASA INPUT_OPT does not accept text label vars at all (not at runtime level)
TODO timera timerb (remember, only within scope; cannot declare var with same name; global shall not be named timera/timerb)
TODO interesting NOP is not compiled
TODO creating packages and such are declarations too (not only var decls)
TODO translation limits
LIMITS
TODO gxtsema gxt key length <8
TODO gxtsema filename (excluding extension must be) <16
TODO label name \<=38
TODO varname <40
TODO scriptname \<=7
TODO scriptnames \<= 300
TODO \<=9216 gvar storage words
TODO \<=16 lvars storage words
TODO \<=255 array size
TODO \<=35000 label refs
TODO \<=255 line
TODO \<=127 string
