= GTA3script Specification
:toc: macro
:toc-title:
:toclevels: 9
:sectnums:
//:revnumber: {release-version}
:revdate: {localdate}
:nofooter:
:idprefix:
:idseparator: -

NOTE: This is a draft. It may be wrong, incomplete and subject to change.

toc::[]

include::00-introduction.adoc[]

include::01-scope.adoc[]

include::02-terms-and-definitions.adoc[]

include::03-notation.adoc[]

include::04-concepts.adoc[]

include::05-elements.adoc[]

include::06-parameters.adoc[]

include::07-command-selectors.adoc[]

include::08-expressions.adoc[]

include::09-statements.adoc[]

include::10-script-file-structure.adoc[]

include::11-supporting-commands.adoc[]

include::12-supporting-command-selectors.adoc[]

include::13-regular-lexical-grammar.adoc[]

include::13-ambiguity.adoc[]

include::13-how-to-miss2.adoc[]

include::14-arachniography.adoc[]

TODO should we fix the floating point literals (e.g. '1.9.2')? I think there are DMA scripts that need this.
TODO list of special command names (user cannot write these, include AND/OR/NOT)
TODO label semantics of start new script (GTA3 allows label: {})
TODO SAN ANDREAS ALLOWS IDENTIFIERS TO BEGIN WITH UNDERSCORES
TODO remember GTASA INPUT_OPT does not accept text label vars at all (not at runtime level)
TODO timera timerb (remember, only within scope; cannot declare var with same name; global shall not be named timera/timerb)
TODO interesting NOP is not compiled
TODO creating packages and such are declarations too (not only var decls)
TODO translation limits
LIMITS
TODO gxtsema gxt key length <8
TODO gxtsema filename (excluding extension must be) <16
TODO label name \<=38
TODO varname <40
TODO scriptname \<=7
TODO scriptnames \<= 300
TODO \<=9216 gvar storage words
TODO \<=16 lvars storage words
TODO \<=255 array size
TODO \<=35000 label refs
TODO \<=255 line
TODO \<=127 string
